### Updates an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Vinicius UPDATED",
  "email": "viniciusvon.contato@gmail.com",
  "address": "Rua 01, SHVP",
  "dateOfBirth": "2004-08-07"
}

###